// DO NOT MODIFY, this file is autogenerated by tools/build.ts
export * from 'firebase/vertexai-preview';
import { ɵzoneWrap } from '@angular/fire';
import {
  getVertexAI as _getVertexAI,
  getGenerativeModel as _getGenerativeModel
} from 'firebase/vertexai-preview';

export const getVertexAI = ɵzoneWrap(_getVertexAI, true);
export const getGenerativeModel = ɵzoneWrap(_getGenerativeModel, true);
