// DO NOT MODIFY, this file is autogenerated by tools/build.ts
export * from 'firebase/ai';
import { ɵzoneWrap } from '@angular/fire';
import {
  getAI as _getAI,
  getGenerativeModel as _getGenerativeModel,
  getLiveGenerativeModel as _getLiveGenerativeModel,
  startAudioConversation as _startAudioConversation
} from 'firebase/ai';

export const getAI = ɵzoneWrap(_getAI, true);
export const getGenerativeModel = ɵzoneWrap(_getGenerativeModel, true);
export const getLiveGenerativeModel = ɵzoneWrap(_getLiveGenerativeModel, true);
export const startAudioConversation = ɵzoneWrap(_startAudioConversation, true);
