// These paths are written to use the dist build
export * from './core/angularfire2.spec';
// export * from './analytics/analytics.spec';
export * from './auth/auth.spec';
// export * from './auth-guard/auth-guard.spec';
// export * from './firestore/firestore.spec';
// export * from './firestore/document/document.spec';
// export * from './firestore/collection/collection.spec';
// export * from './firestore/collection-group/collection-group.spec';
export * from './functions/functions.spec';
// export * from './database/database.spec';
// export * from './database/utils.spec';
// export * from './database/observable/fromRef.spec';
// export * from './database/list/changes.spec';
// export * from './database/list/snapshot-changes.spec';
// export * from './database/list/state-changes.spec';
// export * from './database/list/audit-trail.spec';
// export * from './messaging/messaging.spec';
export * from './remote-config/remote-config.spec';
// export * from './storage/storage.spec';
export * from './performance/performance.spec';
