name: Test and publish

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches:
      - "**"
  release:
    types:
      - published
  schedule:
    - cron: 0 0 * * 1-5

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: '20'
          check-latest: false
          package-manager-cache: false
      - name: angular build cache
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: ./.angular
          key: angular-cache
          lookup-only: true
      - name: node_modules cache
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        id: node_modules_cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-20-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-20-
          lookup-only: true
      - name: Install deps
        if: steps.node_modules_cache.outputs.cache-hit != 'true'
        run: |
          npm ci
      - name: Build
        run: ./tools/build.sh
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: angularfire-${{ github.run_id }}
          path: dist
          retention-days: 1

  test:
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        node: ["20", "22", "24"]
      fail-fast: false
    name: Test Node ${{ matrix.node }} (${{ matrix.os }})
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          package-manager-cache: false
      - name: node_modules cache
        id: node_modules_cache
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-
          lookup-only: true
      - name: Install deps
        if: steps.node_modules_cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Download Artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.1.8
        with:
          name: angularfire-${{ github.run_id }}
          path: dist
      - name: Test Node
        run: |
          npm run build:jasmine
          npm run test:node

  browser:
    runs-on: ${{ matrix.os }}
    needs: build
    name: Test ${{ matrix.browser }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        browser: [ chrome-headless, firefox-headless ]
        # TODO(davideast): Figure out why Safari tests timeout only on CI
        # include:
        # - os: macos-latest
        #   browser: safari
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: 20
          check-latest: false
          package-manager-cache: false
      - name: Setup java
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: node_modules cache
        id: node_modules_cache
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-
          lookup-only: true
      - name: Install deps
        if: steps.node_modules_cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Firebase emulator cache
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: ~/.cache/firebase/emulators
          key: firebase_emulators
          lookup-only: true
      - name: Download Artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.1.8
        with:
          name: angularfire-${{ github.run_id }}
          path: dist
      - name: Test browser
        run: npm run test:${{ matrix.browser }}

  contribute:
    runs-on: ${{ matrix.os }}
    name: Contribute Node ${{ matrix.node }} (${{ matrix.os }})
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        node: ["20"]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          package-manager-cache: false
      - name: node_modules cache
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        id: node_modules_cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-
          lookup-only: true
      - name: Install deps
        if: steps.node_modules_cache.outputs.cache-hit != 'true'
        run: npm ci
      #- name: Lint
      #  run: npm run lint
      - name: Build
        run: npm run build
      - name: Test Node
        run: |
          npm run build:jasmine
          npm run test:node
      - name: Firebase emulator cache
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: ~/.cache/firebase/emulators
          key: firebase_emulators
          lookup-only: true
      - name: Setup java
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Test headless
        run: npm run test:chrome-headless
        # Tests are flaky on Windows
        continue-on-error: ${{ matrix.os == 'windows-latest' }}

  # Break the branch protection test into a seperate step, so we can manage the matrix more easily
  test_and_contribute:
    runs-on: ubuntu-latest
    name: Branch protection
    needs: ['test', 'contribute', 'browser']
    steps:
      - run: true

  publish:
    runs-on: ubuntu-latest
    name: Publish (NPM)
    needs: ['build', 'test', 'browser']
    if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'release' }}
    steps:
      - name: Setup node
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          check-latest: false
          package-manager-cache: false
      - name: 'Download Artifacts'
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.1.8
        with:
          name: angularfire-${{ github.run_id }}
          path: dist
      - name: Publish
        run: |
          cd ./dist/packages-dist
          chmod +x publish.sh
          ./publish.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
